pluginManagement {
    repositories {
        maven { url = uri("https://maven.aliyun.com/repository/gradle-plugin") }
        maven { url = uri("https://maven.aliyun.com/repository/google") }
        maven { url = uri("https://maven.aliyun.com/repository/public") }
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

enableFeaturePreview("VERSION_CATALOGS")
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url = uri("https://maven.aliyun.com/repository/google") }
        maven { url = uri("https://maven.aliyun.com/repository/public") }
        flatDir {
            dirs("${rootDir}/libs")
        }
        google()
        mavenCentral()
    }
}

include ':iconloaderlib'
include 'SettingsLib:HelpUtils'
include 'SettingsLib:RestrictedLockUtils'
include 'SettingsLib:AppPreference'
include 'SettingsLib:SearchWidget'
include 'SettingsLib:LayoutPreference'
include 'SettingsLib:BarChartPreference'
include 'SettingsLib:ActionBarShadow'
include 'SettingsLib:ProgressBar'
include 'SettingsLib:CollapsingToolbarBaseActivity'
include 'SettingsLib:SettingsTheme'
include 'SettingsLib:FooterPreference'
include 'SettingsLib:RadioButtonPreference'
include 'SettingsLib:TwoTargetPreference'
include 'SettingsLib:SettingsTransition'
include 'SettingsLib:Utils'
include 'SettingsLib:SelectorWithWidgetPreference'